[theme]
primaryColor = "#487c79"
backgroundColor = "#f7f7f3"
secondaryBackgroundColor = "#efefea"
textColor = "#193447"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
